### ISSUE TITLE
Question: What interface is used to create the roadmap site? (https://roadmap.leapp.cloud/)

### ISSUE THREAD

**Issue by jimbrig** [Noovolari/leapp-website#4]
Really like the [roadmap website](https://roadmap.leapp.cloud/) you have created with its notion-like interface. I was wondering how this site was built and whether you created it yourself or published via some service like notion.

Thanks in advance!

**Comment by andreacavagna01** [comment]
Its [ProductBoard](https://www.productboard.com) I find it so intuitive

**Comment by jimbrig** [comment]
Thanks @andreacavagna01 looking forward to the growth of leapp!
